<a href="https://colab.research.google.com/github/anish2cod/NerualNetwork/blob/main/neuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.poly1d([1,0,1])


poly1d([1, 0, 1])

In [21]:
np.random.normal(size = (10,2))

array([[-0.19857181,  2.39847493],
       [ 1.21658491, -0.92526387],
       [-0.38603463,  1.165796  ],
       [-0.53754909,  0.80510569],
       [-2.75969271,  0.00575862],
       [-0.46520168,  0.50297423],
       [ 1.2008395 ,  0.23085788],
       [-0.47396705,  0.1543478 ],
       [ 0.29562354, -0.07362469],
       [ 1.77026343,  1.08750753]])

In [3]:
np.array([[1,2,3],[4,5,6]])@np.array([1,2,3])

array([14, 32])

In [ ]:
# class Neuron:
#   def __init__(self, value = 0):
#     self.value = value


In [ ]:
class Functions:


In [25]:
class Layer:
  def __init__(self, number_of_neurons,input_size , activation='relu',dropout=0,weight_init = None):

    self.neurons = None
    #random initilization need to be changed
    self.weights = np.random.normal(size = (number_of_neurons , input_size))
    self.bias = np.random.normal(size = number_of_neurons)
    #need to change
    self.activation = activation
    self.weight_init = weight_init
    self.dropout = dropout

  def Relu(self,x):
    if x > 0:
      return x
    else:
      return 0
  def Relu_diff(self,x):
    if x > 0:
      return 1
    elif x < 0:
      return 0
    else:
      return 1/2

  def Activation(self,x):
    if self.activation == "relu":
      return self.Relu(x)

  def Diff(self,x):
    if self.activation == "relu":
      return self.Relu_diff(x)

  def FeedForward(self,input):
    self.neurons = self.weights @ input + self.bias
    self.neurons = np.array([self.Activation(x) for x in self.neurons])
    return self.neurons

In [26]:
l1 = Layer(10,5,'relu',.3)
neurons = l1.FeedForward(np.array([1,2,3,4,5]))
print(neurons)

[0.         0.         0.         0.         5.27994291 4.28489489
 0.         5.32835778 0.         0.44070511]


array([[ 0.83615839, -1.669184  , -1.39028641,  0.07934635, -0.37729526],
       [ 1.02817628, -1.2746263 , -0.25877198,  0.26844504, -1.27900971],
       [-0.11875769,  0.25159477, -3.21582222, -0.73078042, -0.62917431],
       [-0.83273599, -1.76153882,  0.77138056, -0.76934809, -0.97734054],
       [-0.35748103, -0.79644797,  1.27764086,  0.98415907, -0.27210512],
       [-0.20052384, -0.80171595,  1.76411167, -0.07405385,  0.20248541],
       [-1.79606579, -0.31649887, -0.35368088, -0.41885553,  0.9429455 ],
       [ 2.07567787,  0.17672084,  0.25186229,  1.14984626, -0.33931366],
       [ 1.94095457, -1.65140391, -0.8706204 , -0.66862797, -0.31345882],
       [ 0.19503542, -0.80292198,  1.578009  ,  0.0422147 , -0.76460414]])

In [ ]:
#to solve how to differentiate function using progamming otherwise mannually give the functions of derivatives

In [ ]:
class Sequential:
  #stack the layers and their interactions

In [ ]:
class NN:
  #fit , predict , backpropagation , feedforward etc..