<a href="https://colab.research.google.com/github/anish2cod/NerualNetwork/blob/main/neuralNetwork.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
np.poly1d([1,0,1])


poly1d([1, 0, 1])

In [21]:
np.random.normal(size = (10,2))

array([[-0.19857181,  2.39847493],
       [ 1.21658491, -0.92526387],
       [-0.38603463,  1.165796  ],
       [-0.53754909,  0.80510569],
       [-2.75969271,  0.00575862],
       [-0.46520168,  0.50297423],
       [ 1.2008395 ,  0.23085788],
       [-0.47396705,  0.1543478 ],
       [ 0.29562354, -0.07362469],
       [ 1.77026343,  1.08750753]])

In [43]:
np.random.normal(size = (3 ,4)).T

array([[ 0.69632078, -0.33451948,  1.13469603],
       [ 1.5397437 ,  0.28863741,  0.77685656],
       [-0.3912268 , -0.20181201, -0.28924476],
       [-0.21034399, -0.7000741 ,  1.61014203]])

In [ ]:
# class Neuron:
#   def __init__(self, value = 0):
#     self.value = value


In [30]:
class Functions:
  # defining relu and its derivative
  def Relu(self,x):
    if x > 0:
      return x
    else:
      return 0
  def Relu_diff(self,x):
    if x > 0:
      return 1
    elif x < 0:
      return 0
    else:
      return 1/2


  #defining the active
  def Activation(self,x,activation):
    if activation == "relu":
      return self.Relu(x)

  def Diff(self,x,activation):
    if activation == "relu":
      return self.Relu_diff(x)

In [77]:
class Layer(Functions):
  def __init__(self, number_of_neurons,input_size , activation='relu',dropout=0,weight_init = None):

    self.neurons = None
    #random initilization need to be changed
    self.weights = np.random.normal(size = (number_of_neurons , input_size))
    self.bias = np.random.normal(size = number_of_neurons)
    #need to change
    self.activation = activation
    self.weight_init = weight_init
    self.dropout = dropout



  def FeedForward_L(self,input):
    self.pre_activation = self.weights @ input + self.bias
    self.neurons = np.array([self.Activation(x,self.activation) for x in self.pre_activation])
    return self.neurons

  def BackPropagation_L(self,grad,input):
    grad = grad * np.array([self.Diff(x,self.activation) for x in self.pre_activation])
    self.grad_bias = grad
    self.grad_weights = grad.reshape(-1,1) @ input.reshape(1,-1)
    grad = self.weights.T @ grad
    return grad


In [60]:
np.array([1,2,3]).reshape(-1,1) @ np.array([2,3,5]).reshape(1,-1)

array([[ 2,  3,  5],
       [ 4,  6, 10],
       [ 6,  9, 15]])

In [78]:
l1 = Layer(10,5,'relu',.3)
neurons1 = l1.FeedForward_L(np.array([1,2,3,4,5]))
neurons2 = l1.BackPropagation_L(np.array([i**2 for i in range(10)]),np.array([1,2,3,4,5]))
print(neurons2)

[58.89751407 -0.75611518 84.69703308 27.76254813 45.1669207 ]


In [35]:
l1.weights

array([[-1.84276301,  1.0378904 ,  2.38456917,  1.33953967, -0.11383585],
       [ 0.98107585, -1.00480884, -0.8540857 ,  1.21782257,  0.85263829],
       [-1.43352505, -0.06191701, -0.04110125, -0.23241591, -1.30896832],
       [-0.2306833 , -0.64986126, -1.34438735,  0.42847812, -0.97931412],
       [ 0.23738939, -2.57282653,  2.0148359 , -1.69113665,  0.13591015],
       [ 0.16961517,  1.31972968, -0.38873224,  0.15880831, -0.58776914],
       [-0.2554158 , -0.52799625,  0.43609675, -0.64468221,  1.45638381],
       [ 0.0476412 , -0.02664106,  1.55056712, -1.91034891,  0.36729176],
       [ 0.37158339,  1.12700001,  1.52286597, -1.76669652,  0.5945604 ],
       [ 1.03795255, -1.01088915, -0.09732181,  1.20083524,  0.54765148]])

In [ ]:
#to solve how to differentiate function using progamming otherwise mannually give the functions of derivatives

In [ ]:
class Sequential:
  #stack the layers and their interactions

In [ ]:
class NN:
  #fit , predict , backpropagation , feedforward etc..